# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimdall < Formula
  desc "Secure local SSH vault and workflow CLI."
  homepage "https://github.com/amanthanvi/heimdall"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.2/heimdall-darwin-amd64.tar.gz"
      sha256 "93b84d63e14318a0b1b902c8923237de63d0efa24b8afb2f443814c2041a4e11"

      def install
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.2/heimdall-darwin-arm64.tar.gz"
      sha256 "9f1a6318bad89b090a007ee9dfd6076a7cc01e71184ef93cbd67acb809c03746"

      def install
        bin.install "heimdall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.2/heimdall-linux-amd64.tar.gz"
      sha256 "b9264b6f3c8b4b40a27ea57fb66f8a64f613c9b2bedb2f07fa13801b13d6d2f0"
      def install
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.2/heimdall-linux-arm64.tar.gz"
      sha256 "3affea6c2181805377ba555911ccd2dd80762f26957eed6e3a0d219f1b3399b3"
      def install
        bin.install "heimdall"
      end
    end
  end
end
