# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimdall < Formula
  desc "Secure local SSH vault and workflow CLI."
  homepage "https://github.com/amanthanvi/heimdall"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.7/heimdall-darwin-amd64.tar.gz"
      sha256 "3cf24d5ec04b8e8ad0cb7967921d2ec04e66bc23e7cb432b8d4e9adb88574938"

      define_method(:install) do
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.7/heimdall-darwin-arm64.tar.gz"
      sha256 "000a40b92b9a5bef7bdd24aaaa4e641834a48690a6d58ecdff34aa1582f8f6c4"

      define_method(:install) do
        bin.install "heimdall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.7/heimdall-linux-amd64.tar.gz"
      sha256 "ba8a1c494e46e08e7f88466c60a0be2a779e7cd336edfb049cf262ba036a1ae0"
      define_method(:install) do
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.7/heimdall-linux-arm64.tar.gz"
      sha256 "e408fa79ba6f52457900e8fbb503b43fd552df6287fb287d43e74f7e782146f8"
      define_method(:install) do
        bin.install "heimdall"
      end
    end
  end
end
