# This file was generated by GoReleaser. DO NOT EDIT.
cask "heimdall" do
  name "heimdall"
  desc "Secure local SSH vault and workflow CLI."
  homepage "https://github.com/amanthanvi/heimdall"
  version "0.1.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heimdall"

  on_macos do
    on_intel do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-darwin-amd64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "ea199a5a53e658daa3f7134f6bd07c849f4f431690acf1bc307cc84d6921e987"
    end
    on_arm do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-darwin-arm64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "7d2a01081245eeda3a9e0fbc30fefd5b3025c2af585b1cc38d237c2bbe2064fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-linux-amd64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "8386780216584ae7217bb2084f907add34a1a9288c2cbc58e47547d118fe4a48"
    end
    on_arm do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-linux-arm64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "aaf8b65764fb6959414086aa6eb587166cf04cce93e8243f38a3d3b6a6c7c15d"
    end
  end

  # No zap stanza required
end
