# This file was generated by GoReleaser. DO NOT EDIT.
cask "heimdall" do
  name "heimdall"
  desc "Secure local SSH vault and workflow CLI."
  homepage "https://github.com/amanthanvi/heimdall"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heimdall"

  on_macos do
    on_intel do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-darwin-amd64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "640629315c11abf7c61e5895dbd3d51d3e9202bd5b8c905165610a2e1f17655f"
    end
    on_arm do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-darwin-arm64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "c79d50f28b7f9277d3cefc871706466c9125544bb6392da7eb50355bb929f5ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-linux-amd64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "2060c5dbfe310e5ddfdb73f520f5d69c8934a1d4661180c74988c93cc3a07845"
    end
    on_arm do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-linux-arm64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "dc99a34c3839f437f6342863d70e14214ae7a1716771c5ebec51a3f5f7beff92"
    end
  end

  # No zap stanza required
end
