# This file was generated by GoReleaser. DO NOT EDIT.
cask "heimdall" do
  name "heimdall"
  desc "Secure local SSH vault and workflow CLI."
  homepage "https://github.com/amanthanvi/heimdall"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heimdall"

  on_macos do
    on_intel do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-darwin-amd64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "9e51b7d863a21458f365604d00da8b8dd51ba4708ea912453a2303a993d155da"
    end
    on_arm do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-darwin-arm64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "53cbf3d3e6d99d312f051acd56bebe2c30029ae3974e07c36268178d45ce677d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-linux-amd64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "15eff0b91cc69fd8d37257f8f0c2d5bd6a10cd2e3422a53fa1c0ff6a60320861"
    end
    on_arm do
      url "https://github.com/amanthanvi/heimdall/releases/download/v#{version}/heimdall-linux-arm64.tar.gz",
        verified: "github.com/amanthanvi/heimdall/"
      sha256 "47b41cd95948af16b07e2eb3f498fd9f1dc602a55b424a6b1d9e7cc15b90caa6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/heimdall"]
    end
  end

  # No zap stanza required
end
