# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimdall < Formula
  desc "Secure local SSH vault and workflow CLI."
  homepage "https://github.com/amanthanvi/heimdall"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.11/heimdall-darwin-amd64.tar.gz"
      sha256 "4b2f949c6d423eefe102e877769758c4543909bc06b3b6fa065175b6511d9561"

      define_method(:install) do
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.11/heimdall-darwin-arm64.tar.gz"
      sha256 "98427fab6b7df89e5200dde663b424b1e9d27aae0f5b01062f837000e3847d22"

      define_method(:install) do
        bin.install "heimdall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.11/heimdall-linux-amd64.tar.gz"
      sha256 "c1a8572985081bf2c0c519d5a0a1a6c69767cbca126c217f245ed96267918632"
      define_method(:install) do
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.11/heimdall-linux-arm64.tar.gz"
      sha256 "138c77bcf93c8487ec6ee5acb05750c1e8ff2c0c379f55eac7a937f49344d4ed"
      define_method(:install) do
        bin.install "heimdall"
      end
    end
  end
end
