# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heimdall < Formula
  desc "Secure local SSH vault and workflow CLI."
  homepage "https://github.com/amanthanvi/heimdall"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.6/heimdall-darwin-amd64.tar.gz"
      sha256 "986ccb2f174c159ce75517c05a48453e0bc3e875c84a70ed63736241aa55bdd5"

      define_method(:install) do
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.6/heimdall-darwin-arm64.tar.gz"
      sha256 "0c0471c8649b57bc8eaaed4c76b09988dfbccb892074f0127fa7d9ab5d1e5c51"

      define_method(:install) do
        bin.install "heimdall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.6/heimdall-linux-amd64.tar.gz"
      sha256 "efed389b98c70ba3551d8e912871ce12f98a006f3f8ac5246f7f420db4b5a152"
      define_method(:install) do
        bin.install "heimdall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amanthanvi/heimdall/releases/download/v0.1.6/heimdall-linux-arm64.tar.gz"
      sha256 "3feb5fd1cc647a4eca417c7117f5afcd9da69aec156c2e6b1b90040dce7cd14e"
      define_method(:install) do
        bin.install "heimdall"
      end
    end
  end
end
